[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "webkit-test"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk = "^0.8"
webkit2gtk = "^0.9"

[dependencies.relm]
default-features = false
path = "../../.."

[dependencies.relm-derive]
path = "../../../relm-derive"
